### ISSUE TITLE
Implement publishing on Codex

### ISSUE THREAD

**Issue by m0ar** [desci-labs/nodes#175]
Under a feature flag, enable publishing nodes to codex in parallel with the regular contract registry flow.

# Tasks:
- [x] Deploy the research object model with Ceramic node. Testnet, or isolated but pg-backed instance, probably.
- [x] Setup local dev env publishing to ceramic? I think I prefer `inmemory`, but could do flag for dev cluster.
- [x] Integrate in the nodes app: when the new manifest CID is known (and published to the dpid registry), also create/update the corresponding research object on the ceramic dev cluster.
